### ISSUE TITLE
Explain the keys used and focus the canvas when page is loaded

### ISSUE THREAD

**Issue by YacineF** [ealionel/snake#1]
When the page is loaded, the game starts too quickly to understand what to do. It could be paused to ask if the player is ready and explains the keys.
The canvas is not always focus, so the page doesn't catch the event of key pressed and it's doing nothing.
Kindly

**Comment by ealionel** [comment]
https://github.com/ealionel/snake/commit/7bef941cb6224d2407dfe69aecdd35e3277adcfc#diff-f41e9d04a45c83f3b6f6e630f10117feR41 fixes it
